<?php

require_once dirname(__FILE__)
	. DIRECTORY_SEPARATOR . '..'
	. DIRECTORY_SEPARATOR . '..'
	. DIRECTORY_SEPARATOR . 'TestHelper.php';

class Vidola_Processor_Processors_SpecialCharacterPostDomHandlerTest extends PHPUnit_Framework_TestCase
{
	public function setup()
	{
		$this->handler = new \Vidola\Processor\Processors\SpecialCharacterPostDomHandler();
	}

	/**
	 * @test
	 */
	public function encodesEntities()
	{
		$doc = new \DOMDocument();
		$textNode = $doc->createTextNode('a&b');
		$doc->appendChild($textNode);
		$this->handler->process($doc);
		$this->assertEquals(
			'a&amp;amp;b',	// specialCharacterPostHandler removes the extra &amp;
							// generated by saveXML
			$doc->saveXML($textNode)
		);
	}

	/**
	 * @test
	 */
	public function encodesEmailAdresses()
	{
		$doc = new \DOMDocument();
		$element = $doc->createElement('a', 'my email');
		$doc->appendChild($element);
		$element->setAttribute('href', 'mailto:me@example.com');
		$this->handler->process($doc);
		$this->assertEquals(
			// specialCharacterPostHandler removes the &amp;
			'<a href="&amp;#109;&amp;#97;&amp;#105;&amp;#108;&amp;#x74;&amp;#x6f;&amp;#x3a;m&amp;#101;&amp;#64;&amp;#101;&amp;#x78;&amp;#x61;&amp;#x6d;&amp;#x70;l&amp;#101;&amp;#46;&amp;#99;&amp;#x6f;&amp;#x6d;">&amp;#109;&amp;#x79;&amp;#32;&amp;#x65;&amp;#109;&amp;#x61;i&amp;#108;</a>',
			$doc->saveXML($element)
		);
	}
}